run:
  tests: false
  deadline: 5m

linters-settings:
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - interfacebloat
    - execinquery # deprecated
    - cyclop # duplicate of gocyclo
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - gomnd
    - ireturn
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
