version: 2
project_name: hass-floorplan
dist: dist

gomod:
  proxy: true

builds:
  - main: ./
    binary: "{{ .ProjectName }}"
    goos:
      - js
    goarch:
      - wasm
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
    name_template: '{{ .Binary }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^tests:'
      - '^test:'
      - '^chore:'

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"
